# /partstudios/d/{did}/{wv}/{wvid}/e/{eid}/translations

optns = {
  "allowFaultyParts": False,
  "angularTolerance": 0.001,
  "blobElementId": "string",
  "blobMicroversionId": "string",
  "cloudObjectId": "string",
  "cloudStorageAccountId": "string",
  "colorMethod": "string",
  "configuration": "string",
  "connectionId": "string",
  "createComposite": True,
  "currentSheetOnly": True,
  "destinationName": "string",
  "distanceTolerance": 0,
  "elementId": "string",
  "elementIds": [
    "string"
  ],
  "emailLink": True,
  "emailMessage": "string",
  "emailSubject": "string",
  "emailTo": [
    "string"
  ],
  "extractAssemblyHierarchy": True,
  "flatten": True,
  "flattenAssemblies": True,
  "foreignId": "string",
  "formatName": "string",
  "fromUserId": "string",
  "getyAxisIsUp": True,
  "grouping": True,
  "hideInspectionItems": True,
  "ignoreExportRulesForContents": True,
  "imageHeight": 0,
  "imageWidth": 0,
  "importAppearances": True,
  "importInBackground": True,
  "importMaterialDensity": True,
  "importWithinDocument": True,
  "includeExportIds": True,
  "joinAdjacentSurfaces": True,
  "level": "string",
  "linkDocumentId": "string",
  "linkDocumentWorkspaceId": "string",
  "maximumChordLength": 0.01,
  "notifyUser": True,
  "occurrencesToExport": "string",
  "onePartPerDoc": True,
  "originalForeignId": "string",
  "parentId": "string",
  "partIds": "string",
  "partsExportFilter": {
    "btType": "string",
    "skipAllMesh": True,
    "skipCurves": True,
    "skipPartialMesh": True
  },
  "password": "string",
  "passwordRequired": True,
  "pdfVersion": "string",
  "processedForeignId": "string",
  "projectId": "string",
  "proxyDocumentId": "string",
  "proxyElementId": "string",
  "proxyWorkspaceVersion": "string",
  "proxyWorkspaceVersionId": "string",
  "resolution": "fine",
  "selectablePdfText": True,
  "sendCopyToMe": True,
  "sheetIndices": [
    0
  ],
  "showOverriddenDimensions": True,
  "skipBodyshop": True,
  "sourceName": "string",
  "specifyMaterialData": True,
  "specifyUnits": True,
  "splinesAsPolylines": True,
  "splitAssembliesIntoMultipleDocuments": True,
  "stepParasolidPreprocessingOption": "NO_PRE_PROCESSING",
  "stepVersionString": "string",
  "storeInDocument": True,
  "textAsGeometry": True,
  "textOption": "string",
  "triggerAutoDownload": True,
  "unit": "string",
  "uploadId": "string",
  "useGltfCompression": True,
  "useIGESImportPostProcessing": True,
  "useIgesCompatibilityMode": True,
  "validForDays": 0,
  "versionString": "string"
}